// Unique districts available in the Saafe Yatra crime dataset.
// Total unique districts: 360

const List<String> districts = [
  // "Agar-Malwa",
  "Ahmadabad",
  "Ahmednagar",
  "Aizawl",
  "Aligarh",
  // "Alipurduar",
  "Almora",
  "Alwar",
  "Ambala",
  "Amritsar",
  // "Amroha",
  "Anjaw",
  "Anugul",
  "Anuppur",
  "Araria",
  "Arwal",
  "Ashoknagar",
  "Auraiya",
  "Bagalkote",
  "Bageshwar",
  "Bahraich",
  "Baksa",
  "Balangir",
  "Baleshwar",
  "Ballia",
  "Balrampur",
  "Banka",
  "Baramulla",
  "Bargarh",
  "Barmer",
  "Barpeta",
  "Begusarai",
  "Belagavi",
  "Bengaluru Urban",
  "Betul",
  "Bhadrak",
  "Bhagalpur",
  "Bhandara",
  "Bharatpur",
  "Bharuch",
  "Bhind",
  "Bhojpur",
  "Bhopal",
  "Bidar",
  "Bijnor",
  "Bikaner",
  "Bishnupur",
  "Bokaro",
  "Bongaigaon",
  "Budgam",
  "Bulandshahr",
  "Burhanpur",
  "Chamoli",
  "Champawat",
  "Chandigarh",
  "Changlang",
  "Chatra",
  "Chennai",
  "Chhatrapati Sambhajinagar",
  "Chhotaudepur",
  "Chikkamagaluru",
  "Chittorgarh",
  "Coimbatore",
  "Cuttack",
  "Cyber Crime",
  "Dadra And Nagar Haveli",
  "Dakshina Kannada",
  "Darbhanga",
  "Darjeeling",
  "Datia",
  "Dausa",
  "Deogarh",
  "Deoria",
  "Dhamtari",
  "Dhanbad",
  "Dhar",
  "Dharashiv",
  "Dharwad",
  "Dhenkanal",
  "Dibrugarh",
  "Dima Hasao",
  "Dimapur",
  "Diu",
  "Durg",
  "East Singhbum",
  "Etah",
  "Faridkot",
  "Fatehgarh Sahib",
  "Fatehpur",
  "Firozabad",
  "Gadchiroli",
  "Ganderbal",
  "Ganganagar",
  "Gangtok",
  "Gariyaband",
  "Gautam Buddha Nagar",
  "Gaya",
  "Ghaziabad",
  "Ghazipur",
  "Giridih",
  "Gomati",
  "Gopalganj",
  "Gorakhpur",
  "Gurdaspur",
  "Gurugram",
  "Gyalshing",
  "Hailakandi",
  "Hamirpur",
  "Hardoi",
  "Hassan",
  "Haveri",
  "Hingoli",
  "Hisar",
  "Hnahthial",
  "Hojai",
  "Hooghly",
  "Howrah",
  "Hyderabad",
  "Idukki",
  "Imphal West",
  "Indore",
  "Jabalpur",
  "Jagitial",
  "Jaipur",
  "Jajapur",
  "Jalaun",
  "Jalna",
  "Jammu",
  "Jamnagar",
  "Jamui",
  "Jashpur",
  "Jaunpur",
  "Jayashankar Bhupalapally",
  "Jehanabad",
  "Jhalawar",
  "Jhargram",
  "Jhunjhunu",
  "Jiribam",
  "Jodhpur",
  "Kachchh",
  "Kakching",
  "Kakinada",
  "Kalahandi",
  "Kamareddy",
  "Kamjong",
  "Kamrup",
  "Kandhamal",
  "Kangpokpi",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kapurthala",
  "Karimnagar",
  "Kasaragod",
  "Kasganj",
  "Kathua",
  "Katni",
  "Kendrapara",
  "Kendujhar",
  "Khairagarh-Chhuikhadan-Gandai",
  "Khairthal-Tijara",
  "Khawzawl",
  "Kheda",
  "Kinnaur",
  "Kiphire",
  "Kishanganj",
  "Kishtwar",
  "Kohima",
  "Kolar",
  "Kollam",
  "Kondagaon",
  "Kra Daadi",
  "Krishna",
  "Kushinagar",
  "Lakhimpur",
  "Lalitpur",
  "Latur",
  "Lawngtlai",
  "Lohardaga",
  "Lohit",
  "Longding",
  "Lower Dibang Valley",
  "Lower Subansiri",
  "Lucknow",
  "Ludhiana",
  "Madhepura",
  "Madhubani",
  "Madurai",
  "Mahabubabad",
  "Mahabubnagar",
  "Mahasamund",
  "Mahesana",
  "Mahisagar",
  "Mahoba",
  "Mahrajganj",
  "Malappuram",
  "Malda",
  "Mandla",
  "Mandya",
  "Mansa",
  "Mau",
  "Mayurbhanj",
  "Medak",
  "Meerut",
  "Mirzapur",
  "Moga",
  "Mokokchung",
  "Moradabad",
  "Mumbai",
  "Mumbai Suburban",
  "Munger",
  "Murshidabad",
  "Muzaffarpur",
  "Nadia",
  "Nagaon",
  "Nagapattinam",
  "Nagarkurnool",
  "Nagaur",
  "Nagpur",
  "Nainital",
  "Nalbari",
  "Nalgonda",
  "Nandurbar",
  "Narayanpur",
  "Narmada",
  "Narmadapuram",
  "Navsari",
  "Nawada",
  "Neemuch",
  "New Delhi",
  "Nizamabad",
  "Noney",
  "North",
  "North And Middle Andaman",
  "North Garo Hills",
  "North Goa",
  "North West",
  "Palakkad",
  "Palamu",
  "Panch Mahals",
  "Panchkula",
  "Panna",
  "Papum Pare",
  "Parbhani",
  "Pashchim Champaran",
  "Pathankot",
  "Patiala",
  "Patna",
  "Pauri Garhwal",
  "Peddapalli",
  "Phek",
  "Pondicherry",
  "Prakasam",
  "Prayagraj",
  "Pulwama",
  "Pune",
  "Purba Medinipur",
  "Purnia",
  "Purulia",
  "Rae Bareli",
  "Raichur",
  "Raigarh",
  "Raipur",
  "Rajanna Sircilla",
  "Rajgarh",
  "Rajkot",
  "Rajnandgaon",
  "Rajsamand",
  "Ramanagara",
  "Ramgarh",
  "Ranchi",
  "Ratnagiri",
  "Reasi",
  "Rewari",
  "Rohtak",
  "Rohtas",
  "Rudra Prayag",
  "S.A.S Nagar",
  "Saharanpur",
  "Saharsa",
  "Salem",
  "Samastipur",
  "Samba",
  "Sambhal",
  "Sangareddy",
  "Sangli",
  "Sangrur",
  "Sant Kabir Nagar",
  "Satara",
  "Shahdara",
  "Shahid Bhagat Singh Nagar",
  "Shahjahanpur",
  "Sheohar",
  "Shi Yomi",
  "Shimla",
  "Shopian",
  "Shrawasti",
  "Siang",
  "Siddharthnagar",
  "Siddipet",
  "Sindhudurg",
  "Sirohi",
  "Sirsa",
  "Sitamarhi",
  "Sivaganga",
  "Solan",
  "Solapur",
  "Sonipat",
  "Sonitpur",
  "South 24 Parganas",
  "South Andamans",
  "South Garo Hills",
  "South Salmara Mancachar",
  "South Tripura",
  "South West",
  "Sri Muktsar Sahib",
  "Sri Potti Sriramulu Nellore",
  "Srikakulam",
  "Srinagar",
  "Sundargarh",
  "Surat",
  "Surguja",
  "Tamenglong",
  "Tarn Taran",
  "Tengnoupal",
  "Thanjavur",
  "The Nilgiris",
  "Thiruvallur",
  "Thiruvananthapuram",
  "Thiruvarur",
  "Thrissur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Tuensang",
  "Tumakuru",
  "Udam Singh Nagar",
  "Udhampur",
  "Udupi",
  "Ujjain",
  "Ukhrul",
  "Unakoti",
  "Upper Siang",
  "Upper Subansiri",
  "Uttar Bastar Kanker",
  "Uttar Dinajpur",
  "Uttar Kashi",
  "Vadodara",
  "Varanasi",
  "Vijayapura",
  "Villupuram",
  "Virudhunagar",
  "Visakhapatnam",
  "Wanaparthy",
  "Warangal",
  "Wayanad",
  "West Jaintia Hills",
  "West Karbi Anglong",
  "West Khasi Hills",
  "West Singhbhum",
  "Yadgir",
];
